[package]
name = "kaito"
version = "0.1.0"
authors = ["Mats A. <mats@mats.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
arc-swap = "1.2"
async-mutex = "1.4.0"
async-trait = "0.1"
bitflags = "1.2"
crossbeam = "0.8.0"
dashmap = "4.0.2"
futures = "0.3"
glob = "0.3.0"
governor = "0.3.2"
hyper = { version = "0.14", features = [ "stream", "client", "http1" ] }
hyper-tls = "0.5"
mlua = { version = "0.5.1", features = [ "lua54", "send" ] }
once_cell = "1.5.2"
paste = "1.0"
tokio = { version = "1.2.0", features = ["macros", "rt-multi-thread", "time"] }
serde = "1.0"
serde_derive = "1.0"
serenity = { version = "0.10", default-features = false, features = ["client", "cache", "gateway", "rustls_backend", "model"] }
thiserror = "1.0"
toml = "0.5"
sqlx = { version = "0.5.1", features = ["sqlite", "runtime-async-std-rustls"] }
url = "2.2.0"
