[package]
name = "kaito"
version = "0.1.0"
authors = ["Mats A. <mats@mats.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
tokio = { version = "0.2", features = ["macros"] }
serenity = "0.9"
thiserror = "1.0"
