[package]
name = "kaito"
version = "0.1.0"
authors = ["Mats A. <mats@mats.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bitflags = "1.2"
dashmap = "3.11.10"
futures = "0.3"
parking_lot = "0.11"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
serde = "1.0"
serde_derive = "1.0"
serenity = { version = "0.9", default-features = false, features = ["client", "cache", "gateway", "rustls_backend", "model"] }
thiserror = "1.0"
toml = "0.5"
